/**
 * MarkdownBridge: the first AgentBridge representation — renders
 * AgentTaskPackage into a fixed, deterministic Markdown document an external
 * Executor Agent can consume. Pure string generation: no file I/O, no Agent
 * execution, no randomness — identical input yields byte-identical output.
 * @module @xiaoxie-ide/dsh-devflow/markdown-bridge
 */

import { assertSupportedProtocolVersion, validateTaskPackage, type AgentBridge } from './bridge.ts'
import type { AgentResultPackage, AgentTaskPackage } from './protocol.ts'
import type { ResultVerdict } from './types.ts'

/** The fixed document heading. */
const DOCUMENT_TITLE = '# DevFlow Task'
/** The fixed result document heading. */
const RESULT_DOCUMENT_TITLE = '# DevFlow Result'
/** The fixed generator attribution line. */
const GENERATED_BY = 'Generated By: DevFlow'
/** A fence line that may wrap the result document. */
const FENCE_LINE = /^(?:```|~~~)/
/** Every section heading a result document may carry. */
const RESULT_SECTIONS = new Set([
  'Metadata', 'Summary', 'Changes', 'Verification', 'Issues', 'Next Steps',
  'Modified Files', 'Tool Step Count', 'Completed Criteria',
])

/**
 * A result document that could not be accepted, with the bounded reason list.
 *
 * `problems` names only what is wrong with the document (missing section, key,
 * or an out-of-range verdict) — never the model's raw reply, so the list is safe
 * to persist in a report summary and to show in a tool error.
 */
export class ResultParseError extends Error {
  constructor(readonly problems: readonly string[]) {
    super(`Invalid AgentResultPackage: ${problems.join('; ')}`)
    this.name = 'ResultParseError'
  }
}

/** A heading line's text, without markdown closing hashes. */
function headingText(line: string): string | undefined {
  const match = /^(#{1,6})\s+(.*?)\s*#*\s*$/.exec(line.trim())
  return match?.[2]
}

/**
 * Locate the result document inside one Agent reply.
 *
 * A fixed Agent often wraps the document in prose or a fenced block even when
 * told not to; the parse therefore starts at the `# DevFlow Result` heading
 * wherever it appears, and stops at the block's end (a closing fence or the next
 * top-level heading). Only a reply without that heading has no document at all.
 * @param content - the Agent reply.
 * @returns the document lines after the heading, or undefined when absent.
 */
function extractResultDocument(content: string): string[] | undefined {
  const lines = content.split(/\r?\n/)
  const headingIndex = lines.findIndex(line => headingText(line) === RESULT_DOCUMENT_TITLE.slice(2))
  if (headingIndex === -1) return undefined
  const body: string[] = []
  for (let index = headingIndex + 1; index < lines.length; index += 1) {
    const line = lines[index] ?? ''
    if (FENCE_LINE.test(line.trim())) break
    const heading = headingText(line)
    if (heading !== undefined && !RESULT_SECTIONS.has(heading) && body.some(entry => entry.trim() !== '')) break
    body.push(line)
  }
  return body
}

function bulletList(items: readonly string[]): string {
  return items.map(item => `- ${item}`).join('\n')
}

/** Render the File Scope section; `Not specified` when the package carries none. */
function fileScopeSection(pkg: AgentTaskPackage): string {
  const scope = pkg.fileScope
  return scope !== undefined && scope.length > 0
    ? bulletList(scope)
    : 'Not specified'
}

/** Render the optional numeric ScopeGuard task limits. */
function taskBoundarySection(pkg: AgentTaskPackage): string {
  const scope = pkg.scopeGuard
  if (scope === undefined) return 'Project default applies'
  return [
    `Maximum Modified Files: ${scope.maxModifiedFiles}`,
    `Maximum Tool Steps: ${scope.maxToolSteps}`,
    'Completion Criteria:',
    bulletList(scope.completionCriteria),
  ].join('\n')
}

/** Split a result document into its `## <name>` sections, in document order. */
function splitSections(lines: readonly string[]): Map<string, string[]> {
  const sections = new Map<string, string[]>()
  let current: string | undefined
  for (const line of lines) {
    const match = /^##\s+(.+?)\s*$/.exec(line)
    if (match !== null && match[1] !== undefined) {
      current = match[1].trim()
      sections.set(current, [])
      continue
    }
    if (current !== undefined) {
      sections.get(current)?.push(line)
    }
  }
  return sections
}

/** Parse one `Key: value` pair; undefined for lines without the separator. */
function keyValue(line: string): [string, string] | undefined {
  const match = /^([A-Za-z][A-Za-z ]*):\s*(.*)$/.exec(line)
  if (match === null || match[1] === undefined || match[2] === undefined) return undefined
  return [match[1].trim(), match[2].trim()]
}

/** Parse one review verdict from result metadata. */
function parseVerdict(metadata: ReadonlyMap<string, string>): ResultVerdict {
  const verdict = metadata.get('Verdict')
  if (verdict === 'accepted' || verdict === 'changes-requested' || verdict === 'rejected') return verdict
  const shown = verdict === undefined ? '(missing)' : JSON.stringify(verdict.slice(0, 40))
  throw new ResultParseError([`verdict ${shown} is not accepted|changes-requested|rejected`])
}

/** Parse one non-negative integer result metric. */
function parseCount(metadata: ReadonlyMap<string, string>, key: string): number {
  const raw = metadata.get(key)
  if (raw === undefined) {
    throw new ResultParseError([`missing ${key}`])
  }
  const value = Number(raw)
  if (!Number.isSafeInteger(value) || value < 0) {
    throw new ResultParseError([`${key} must be a non-negative integer`])
  }
  return value
}

/** Extract `- item` list entries in order, ignoring non-list lines and blanks. */
function listItems(lines: readonly string[]): string[] {
  const items: string[] = []
  for (const line of lines) {
    const match = /^-\s+(.*)$/.exec(line)
    if (match !== null && match[1] !== undefined) items.push(match[1])
  }
  return items
}

/**
 * Parse one Markdown result document into a result package. Simple and
 * stable: the document is split on `##` headings and sections are mapped by
 * name; `protocolVersion`, `taskId`, and `summary` are required and fail
 * loud, the list sections default to []. No Markdown AST is involved.
 * @param markdown - the result document produced by an external Agent.
 * @returns the validated result package.
 */
export function parseResultMarkdown(markdown: string): AgentResultPackage {
  const document = extractResultDocument(markdown)
  if (document === undefined) {
    throw new ResultParseError([`missing the ${JSON.stringify(RESULT_DOCUMENT_TITLE)} heading`])
  }
  const sections = splitSections(document)
  const sectionText = (name: string): string => (sections.get(name) ?? []).join('\n').trim()
  const sectionLines = (name: string): string[] => sections.get(name) ?? []

  const metadata = new Map<string, string>()
  for (const line of sectionLines('Metadata')) {
    const pair = keyValue(line)
    if (pair !== undefined) metadata.set(pair[0], pair[1])
  }
  const protocolVersion = metadata.get('Protocol Version')
  if (protocolVersion === undefined || protocolVersion === '') {
    throw new ResultParseError(['missing protocolVersion'])
  }
  try {
    assertSupportedProtocolVersion(protocolVersion)
  } catch {
    throw new ResultParseError([`unsupported protocolVersion ${JSON.stringify(protocolVersion.slice(0, 24))}`])
  }
  const taskId = metadata.get('Task ID')
  if (taskId === undefined || taskId === '') {
    throw new ResultParseError(['missing taskId'])
  }
  const summary = sectionText('Summary')
  if (summary === '') {
    throw new ResultParseError(['missing summary'])
  }
  return {
    protocolVersion,
    taskId,
    verdict: parseVerdict(metadata),
    summary,
    changes: listItems(sectionLines('Changes')),
    verification: listItems(sectionLines('Verification')),
    issues: listItems(sectionLines('Issues')),
    nextSteps: listItems(sectionLines('Next Steps')),
    ...(metadata.get('Modified File Count') === undefined ? {} : { modifiedFiles: listItems(sectionLines('Modified Files')) }),
    ...(metadata.get('Tool Step Count') === undefined ? {} : { toolStepCount: parseCount(metadata, 'Tool Step Count') }),
    ...(sections.has('Completed Criteria') ? { completedCriteria: listItems(sectionLines('Completed Criteria')) } : {}),
  }
}

/** Render one task package into the fixed Markdown template. Pure and deterministic. */
export function renderTaskMarkdown(pkg: AgentTaskPackage): string {
  const instructions = pkg.instructions === '' ? '(none)' : pkg.instructions
  const criteria = pkg.acceptanceCriteria.length > 0 ? bulletList(pkg.acceptanceCriteria) : '(none)'
  const lines = [
    DOCUMENT_TITLE,
    '',
    '## Metadata',
    '',
    `Protocol Version: ${pkg.protocolVersion}`,
    `Task ID: ${pkg.taskId}`,
    `Role: ${pkg.role}`,
    GENERATED_BY,
    '',
    '## Project Context',
    '',
    `Project: ${pkg.projectContext.name} (${pkg.projectContext.id})`,
    `Stage: ${pkg.projectContext.currentStage}`,
    `Goal: ${pkg.projectContext.goal}`,
    '',
    '## Task Description',
    '',
    `### ${pkg.task.title}`,
    '',
    pkg.task.description,
    '',
    '## Instructions',
    '',
    instructions,
    '',
    '## Acceptance Criteria',
    '',
    criteria,
    '',
    '## File Scope',
    '',
    fileScopeSection(pkg),
    '',
    '## Task Boundaries',
    '',
    taskBoundarySection(pkg),
    '',
    '## Required Result Format',
    '',
    'Your final response must contain only one complete result document in the exact format below.',
    'Do not omit, rename, or reorder any required heading or metadata key.',
    'Use the exact Protocol Version and Task ID already written in the template.',
    'Verdict must be exactly one of: accepted, changes-requested, rejected.',
    'Summary must be non-empty. Keep Changes, Verification, Issues, and Next Steps; write `- None` when a list has no other item.',
    'Do not output any text or fenced code block before or after the result document.',
    '',
    RESULT_DOCUMENT_TITLE,
    '',
    '## Metadata',
    '',
    `Protocol Version: ${pkg.protocolVersion}`,
    `Task ID: ${pkg.taskId}`,
    'Verdict: accepted|changes-requested|rejected',
    '',
    '## Summary',
    '',
    '<non-empty summary>',
    '',
    '## Changes',
    '',
    '- <change or None>',
    '',
    '## Verification',
    '',
    '- <verification or None>',
    '',
    '## Issues',
    '',
    '- <issue or None>',
    '',
    '## Next Steps',
    '',
    '- <next step or None>',
    '',
  ]
  return lines.join('\n')
}

/**
 * The Markdown bridge: renders task packages to Markdown and (from Task-013
 * on) parses result Markdown back into result packages.
 */
export class MarkdownBridge implements AgentBridge {
  /** Stable bridge kind. */
  readonly name = 'markdown' as const

  /**
   * Render one task package into Markdown. The package is audited first;
   * a non-exportable package fails loud.
   * @param pkg - the task package to export.
   * @returns the rendered Markdown document.
   */
  exportTask(pkg: AgentTaskPackage): string {
    const problems = validateTaskPackage(pkg)
    if (problems.length > 0) {
      throw new Error(`Invalid AgentTaskPackage: ${problems.join('; ')}`)
    }
    return renderTaskMarkdown(pkg)
  }

  /**
   * Parse one Markdown result document back into a result package.
   * @param content - the result document produced by an external Agent.
   * @returns the validated result package.
   */
  importResult(content: string): AgentResultPackage {
    return parseResultMarkdown(content)
  }

  /**
   * Audit one task package before export.
   * @param pkg - the package to audit.
   * @returns one problem per finding; an empty list means exportable.
   */
  validate(pkg: AgentTaskPackage): readonly string[] {
    return validateTaskPackage(pkg)
  }
}
